# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the server code into the container
COPY . .

# Set the Python path to include the current directory
ENV PYTHONPATH=/app/app

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run the application
CMD ["python", "app/__init__.py"]
